name       : ecl
version    : 16.0.0
release    : 1
homepage   : https://common-lisp.net/project/ecl/
source     :
    - https://common-lisp.net/project/ecl/files/ecl-16.0.0.tgz : 343ed4c3e4906562757a6039b85ce16d33dd5e8001d74004936795983e3af033
license    : GPL-2.0
summary    : ECL is an interpreter of the Common-Lisp language
description: |
    ECL (Embeddable Common-Lisp) is an interpreter of the Common-Lisp language as described in the X3J13 Ansi specification, 
    featuring CLOS (Common-Lisp Object System), conditions, loops, etc, plus a translator to C, which can produce standalone executables.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

